/**
 * Script to generate pre-computed BaZi chart data for famous people
 * Run with: npx ts-node --esm scripts/generateFamousCharts.ts
 */

// Import FAMOUS_PEOPLE from source file (need to use ts-node to handle the TS import)
import { FAMOUS_PEOPLE } from '../src/data/famousPeople';

// Use full list
const FAMOUS_PEOPLE_SUBSET = FAMOUS_PEOPLE;

const API_URL = 'https://astro-api-1qnc.onrender.com/api/v1/chinese/bazi';

async function fetchChart(person: typeof FAMOUS_PEOPLE_SUBSET[0]) {
    const apiKey = process.env.ASTRO_API_KEY;
    if (!apiKey) {
        throw new Error('ASTRO_API_KEY not set');
    }

    const body = {
        year: person.birth.year,
        month: person.birth.month,
        day: person.birth.day,
        hour: person.birth.hour,
        minute: person.birth.minute,
        city: person.birth.city,
        time_mode: 'true_solar_absolute',
    };

    console.log(`Fetching chart for ${person.name}...`);

    const response = await fetch(API_URL, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'x-api-key': apiKey,
        },
        body: JSON.stringify(body),
    });

    if (!response.ok) {
        throw new Error(`API error for ${person.name}: ${response.status}`);
    }

    return response.json();
}

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load environment variables from .env.local
dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

async function main() {
    const results: Record<string, unknown>[] = [];

    // Check if key is loaded
    if (!process.env.ASTRO_API_KEY) {
        console.error('Error: ASTRO_API_KEY not found in .env.local');
        // Try to fallback to NEXT_PUBLIC if available (though unlikely for a backend key)
        if (process.env.NEXT_PUBLIC_ASTRO_API_KEY) {
            console.log('Using NEXT_PUBLIC_ASTRO_API_KEY instead');
            process.env.ASTRO_API_KEY = process.env.NEXT_PUBLIC_ASTRO_API_KEY;
        } else {
            console.log('Available env keys:', Object.keys(process.env).filter(k => k.includes('KEY')));
            process.exit(1);
        }
    }

    const headers = {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ASTRO_API_KEY || ''
    };

    console.log('Starting chart generation for', FAMOUS_PEOPLE_SUBSET.length, 'people...');

    for (const person of FAMOUS_PEOPLE_SUBSET) {
        try {
            const chart = await fetchChart(person);
            results.push({
                id: person.id,
                name: person.name,
                category: person.category,
                birth: person.birth,
                brief: person.brief,
                chart: chart,
            });
            console.log(`✓ ${person.name} done`);
            // Wait 500ms between requests to avoid rate limiting
            await new Promise(r => setTimeout(r, 500));
        } catch (error) {
            console.error(`✗ ${person.name} failed:`, error);
        }
    }

    const outputPath = path.resolve(__dirname, '../src/data/famousPeopleCharts.ts');
    const content = `// Generated by scripts/generateFamousCharts.ts
// Do not edit manually

export const FAMOUS_CHARTS_DATA = ${JSON.stringify(results, null, 2)};
`;

    fs.writeFileSync(outputPath, content);
    console.log(`\nSuccessfully wrote ${results.length} charts to ${outputPath}`);
}

main().catch(console.error);
